SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE IMPRIMIR(DATO IN VARCHAR2)
AS
BEGIN
DBMS_OUTPUT.PUT_LINE(DATO);
END;

BEGIN
IMPRIMIR('HOLA MUNDO');
END;

CREATE OR REPLACE PROCEDURE ANIOS_DIAS(ANIOS IN INTEGER, DIAS OUT INTEGER)
AS
BEGIN
DIAS := ANIOS * 365;
END;

DECLARE 
D INTEGER;
BEGIN
ANIOS_DIAS(25, D);
DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES: ' || D);
END;