CREATE TABLE USUARIO_XXX(
  ID INTEGER,
  EMAIL VARCHAR2(120),
  EDAD INTEGER
);

CREATE OR REPLACE TRIGGER DISPARADOR_USUARIO_XXX BEFORE INSERT ON USUARIO_XXX FOR EACH ROW
BEGIN
IF :NEW.EDAD < 18 OR length(:NEW.EMAIL) < 3 THEN
  RAISE_APPLICATION_ERROR(-20001, 'LO SIENTO ERES PEQUEÑO');
END IF;
END;

CREATE TABLE USUARIOS(
  ID INTEGER,
  EDAD INTEGER,
  EMAIL VARCHAR2(120)
);

CREATE TABLE USUARIOS_MENORES(
  ID INTEGER,
  EDAD INTEGER,
  EMAIL VARCHAR2(120)
);

CREATE TABLE USUARIOS_MAYORES(
  ID INTEGER,
  EDAD INTEGER,
  EMAIL VARCHAR2(120)
);

CREATE OR REPLACE TRIGGER DISPARADOR_USUARIOS AFTER INSERT ON USUARIOS FOR EACH ROW
BEGIN
IF :NEW.EDAD < 18 THEN
  INSERT INTO USUARIOS_MENORES VALUES(:NEW.ID, :NEW.EDAD, :NEW.EMAIL);
END IF;
IF :NEW.EDAD >= 18 THEN
  INSERT INTO USUARIOS_MAYORES VALUES(:NEW.ID, :NEW.EDAD, :NEW.EMAIL);
END IF;
END;
