SET SERVEROUTPUT ON;

CREATE TABLE PRUEBA_EXCEPCIONES (ID_PRUEBA INTEGER, NOMBRE VARCHAR2(120));

BEGIN
FOR I IN 1..10 LOOP
 INSERT INTO PRUEBA_EXCEPCIONES VALUES (I, 'RAFAEL');
END LOOP;
END;

SELECT * FROM PRUEBA_EXCEPCIONES;

DECLARE
MI_USUARIO PRUEBA_EXCEPCIONES.NOMBRE%TYPE;
BEGIN
SELECT NOMBRE INTO MI_USUARIO FROM PRUEBA_EXCEPCIONES;
DBMS_OUTPUT.PUT_LINE('USUARIO ENCONTRADO PARA OPERARLO: ' || MI_USUARIO);
EXCEPTION
 WHEN TOO_MANY_ROWS THEN
 DBMS_OUTPUT.PUT_LINE('SE LANZO UNA EXCEPCION PORQUE HUBO MUCHAS OCURRENCIAS');
END;