CREATE TABLE USUARIO_XXX(ID INTEGER, EMAIL VARCHAR2(120), EDAD INTEGER);

CREATE OR REPLACE PROCEDURE GUARDAR_USUARIO_XXX(ID IN INTEGER, EMAIL IN VARCHAR2, EDAD IN INTEGER)
AS
BEGIN
IF EDAD < 18 THEN
 RAISE_APPLICATION_ERROR(-20002, 'LO SIENTO ERES MUY PEQUEÑO');
END IF;
INSERT INTO USUARIO_XXX VALUES (ID, EMAIL, EDAD);
END;

BEGIN
GUARDAR_USUARIO_XXX(1, 'ALGO@ALGO.COM', 16);
END;

SELECT * FROM USUARIO_XXX;