SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE EFICIENCIA_DEVELOPER (MY_ID_DEVELOPER IN INTEGER, TAREAS OUT VARCHAR2)
AS
CURSOR CURSOR_TAREAS IS SELECT ID_TAREA FROM TAREA WHERE ID_DEVELOPER=MY_ID_DEVELOPER AND COMPLETADA='N';
BEGIN
TAREAS := 'El siguiente desarrollador tiene por completar las tareas cuyos ids son: ';
FOR TAREA IN CURSOR_TAREAS LOOP
 TAREAS := TAREAS || TAREA.ID_TAREA || ', ';
END LOOP;
END;

DECLARE
TEXTO VARCHAR2(255);
BEGIN
EFICIENCIA_DEVELOPER(1, TEXTO);
DBMS_OUTPUT.PUT_LINE(TEXTO);
END;

CREATE OR REPLACE PROCEDURE ANALZIAR_TAREA_INCOMPLETA (MY_ID_DEVELOPER IN INTEGER, MY_ID_TAREA IN INTEGER, MY_PORCENTAGE OUT INTEGER, MY_FECHA OUT DATE)
AS
BEGIN
SELECT PORCIENTO_COMPLETADA INTO MY_PORCENTAGE FROM TAREA WHERE ID_TAREA=MY_ID_TAREA AND ID_DEVELOPER=MY_ID_DEVELOPER;
SELECT FECHA INTO MY_FECHA FROM TAREA WHERE ID_TAREA=MY_ID_TAREA AND ID_DEVELOPER=MY_ID_DEVELOPER;
END;

DECLARE
PORCENTAGE INTEGER;
FECHA DATE;
BEGIN
ANALZIAR_TAREA_INCOMPLETA(1, 1, PORCENTAGE, FECHA);
DBMS_OUTPUT.PUT_LINE('PORCENTAGE: ' || PORCENTAGE || ' FECHA: ' || FECHA);
END;

CREATE OR REPLACE PROCEDURE EFICIENCIA_EMPRESA(PORCENTAGE OUT FLOAT)
AS
TOTAL_TAREAS INTEGER;
TOTAL_PORCIENTO INTEGER;
CURSOR CURSOR_TAREAS IS SELECT * FROM TAREA;
BEGIN
TOTAL_PORCIENTO := 0;
TOTAL_TAREAS := 0;
FOR TAREA IN CURSOR_TAREAS LOOP
 TOTAL_PORCIENTO := TOTAL_PORCIENTO + TAREA.PORCIENTO_COMPLETADA;
 TOTAL_TAREAS := TOTAL_TAREAS + 1;
END LOOP;
PORCENTAGE := TOTAL_PORCIENTO/TOTAL_TAREAS;
END;

DECLARE
VALOR FLOAT;
BEGIN
EFICIENCIA_EMPRESA(VALOR);
DBMS_OUTPUT.PUT_LINE(VALOR);
END;


