CREATE TABLE ALGODON (ID_ALGO INTEGER, NOMBRE VARCHAR2(120), EDAD INTEGER,
CONSTRAINT PK_ID_ALGODON PRIMARY KEY(ID_ALGO) );

CREATE SEQUENCE SECUENCIA_ALGODON
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE OR REPLACE PROCEDURE GUARDAR_ALGODON(MY_ID_ALGODON OUT INTEGER, MY_NOMBRE IN VARCHAR2, MY_EDAD IN INTEGER)
AS
BEGIN
SELECT SECUENCIA_ALGODON.NEXTVAL INTO MY_ID_ALGODON FROM DUAL;
INSERT INTO ALGODON VALUES(MY_ID_ALGODON, MY_NOMBRE, MY_EDAD);
END;

DECLARE
VALOR INTEGER;
BEGIN
GUARDAR_ALGODON(VALOR, 'RAFAEL', 25);
DBMS_OUTPUT.PUT_LINE('ID: ' || VALOR);
END;

SELECT * FROM ALGODON;