/* TAREA */
CREATE TABLE USARIO_REG(
  ID INTEGER,
  EMAIL VARCHAR2(120),
  EDAD INTEGER,
  FECHA_CORTE DATE
  );
/* INSERTAR 3 REGISTROS SIN EL DATO FECHA */
/* SI EL RANGO DE HORA ESTA EN 8PM A 10PM IMPERDIRE */
