/* MI PRIMER STORED PROCEDURE */
/* UN PROCEDIMIENTO ALMACENADO PUEDE INVOCAR UNO O MAS PROCEDIMIENTOS YA ALMACENADO */

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE hola_mundo
AS
MENSAJITO VARCHAR2(250);
BEGIN
MENSAJITO := 'MIS PRIMEROS PININOS CON LOS PROCEDIMIENTOS';
DBMS_OUTPUT.PUT_LINE(MENSAJITO);
END;

BEGIN
  HOLA_MUNDO();
END;
