CREATE TABLE DEVELOPER(
  ID_DEVELOPER INTEGER,
  NOMBRE VARCHAR2(120),
  EMAIL VARCHAR2(120),
  CONSTRAINT ID_DEVELOPER PRIMARY KEY(ID_DEVELOPER)
);

CREATE TABLE TAREA(
  ID_TAREA INTEGER,
  ID_DEVELOPER INTEGER,
  DESCRIPCION VARCHAR2(500),
  COMPLETADA CHAR,
  PORCIENTO_COMPLETADA INTEGER,
  FECHA DATE,
  CONSTRAINT ID_TAREA PRIMARY KEY(ID_TAREA),
  CONSTRAINT ID_DEELOPER_TAREA FOREIGN KEY(ID_DEVELOPER) REFERENCES DEVELOPER(ID_DEVELOPER)
);

CREATE SEQUENCE SEC_DEVELOPER
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE SEV_TAREA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE OR REPLACE PROCEDURE GUARDAR_DEVELOPER(ID_DEVELOPER OUT INTEGER, MY_NOMBRE IN VARCHAR2, MY_EMAIL IN VARCHAR2)
AS
BEGIN
SELECT SEC_DEVELOPER.NEXTVAL INTO ID_DEVELOPER FROM DUAL;
INSERT INTO DEVELOPER VALUES(ID_DEVELOPER, MY_NOMBRE, MY_EMAIL);
END;

CREATE OR REPLACE PROCEDURE GUARDAR_TAREA(ID_TAREA OUT INTEGER, MY_ID_DEVELOPER IN INTEGER, MY_DESCRIPCION VARCHAR2)
AS
BEGIN
SELECT SEV_TAREA.NEXTVAL INTO ID_TAREA FROM DUAL;
INSERT INTO TAREA VALUES(ID_TAREA, MY_ID_DEVELOPER, MY_DESCRIPCION, 'N', 0, SYSDATE);
END;

DECLARE
ID_DEVELOPER INTEGER;
ID_TAREA INTEGER;
BEGIN
GUARDAR_DEVELOPER(ID_DEVELOPER, 'BRENDA', 'BRENDA@GMAIL.COM');
GUARDAR_TAREA(ID_TAREA, ID_DEVELOPER, 'CREACION DE LA PAGINA WEB');

GUARDAR_DEVELOPER(ID_DEVELOPER, 'JOSE OMAR', 'OMAR@YAHOO.COM');
GUARDAR_TAREA(ID_TAREA, ID_DEVELOPER, 'CREACION DE LAS TABLAS');

GUARDAR_DEVELOPER(ID_DEVELOPER, 'VICTOR ANGEL', 'VICTOR@HOTMAIL.COM');
GUARDAR_TAREA(ID_TAREA, ID_DEVELOPER, 'PROGRAMACION DE LOS PROCEDIMIENTOS');

GUARDAR_DEVELOPER(ID_DEVELOPER, 'LESLYE', 'LESLIE@LIVE.COM');
GUARDAR_TAREA(ID_TAREA, ID_DEVELOPER, 'PROGRAMACION DE LOS SERVICIOS WEB');
END;

SELECT * FROM DEVELOPER;
SELECT * FROM TAREA;

CREATE OR REPLACE PROCEDURE ACTUALIZAR_TAREA(MY_ID_TAREA IN INTEGER, MY_ID_DEVELOPER IN INTEGER, MY_PORCIENTO_COMPLETADA IN INTEGER)
AS
PORCENTAJE_ACTUAL INTEGER;
PORCENTAJE_TOTAL INTEGER;
BEGIN
SELECT PORCIENTO_COMPLETADA INTO PORCENTAJE_ACTUAL FROM TAREA WHERE ID_TAREA=MY_ID_TAREA;
PORCENTAJE_TOTAL := PORCENTAJE_ACTUAL + MY_PORCIENTO_COMPLETADA;
IF PORCENTAJE_TOTAL > 100 THEN
  RAISE_APPLICATION_ERROR(-20003, 'LO SIENTO EL PORCENTAGE ES MAYOR A 100%');
END IF;
IF PORCENTAJE_TOTAL = 100 THEN
  UPDATE TAREA SET PORCIENTO_COMPLETADA=100, COMPLETADA='S',FECHA=SYSDATE WHERE ID_TAREA=MY_ID_TAREA;
END IF;
UPDATE TAREA SET PORCIENTO_COMPLETADA=PORCENTAJE_TOTAL, FECHA=SYSDATE WHERE ID_TAREA=MY_ID_TAREA;
END;

BEGIN
ACTUALIZAR_TAREA(1, 1, 30);
END;

BEGIN
ACTUALIZAR_TAREA(1, 1, 40);
END;
